### PR TITLE
Fix: Tell offender what bad word they used (#1)

### PR DESCRIPTION
**Pull request by Lain-x86**

### CODE REVIEW

**Comment by coatlessali** [comment]
The main issue with this is that we're trying to avoid having the bad word said anywhere in a server. A solution where the bot DMs the user would be preferred.

**Comment by Lain-x86** [comment]
Ooohh, ok I can refactor the code for that.

**Comment by Lain-x86** [comment]
Alright done

**Comment by coatlessali** [comment]
I'm really new to GitHub and using git in general, how would I test this before I merge it?

**Comment by Lain-x86** [comment]
You would clone my fork ([https://github.com/shadawcraw/FennecBot.git](https://github.com/shadawcraw/FennecBot.git)) using `git clone https://github.com/shadawcraw/FennecBot.git` and then you can setup the bot and run it to test the changes.

**Pull request merged**
